repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-docstrings-complete==1.3.0
#-   repo: local
#    hooks:
#    -   id: coverage
#        name: coverage
#        entry: pytest --cov=src
#        language: system
#        pass_filenames: false
#        always_run: true